# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|

  config.vm.provider :openstack do |os|
    os.openstack_auth_url    = ENV['OS_AUTH_URL']
    os.tenant_name           = ENV['OS_TENANT_NAME']
    os.username              = ENV['OS_USERNAME']
    os.password              = ENV['OS_PASSWORD']
    os.floating_ip_pool      = ENV['OS_FLOATING_IP_POOL']
    os.flavor                = ENV['OS_FLAVOR']
    os.image                 = ENV['OS_IMAGE']
    os.security_groups       = ['sg']
    os.networks             << 'heat-net'
    os.stacks               << {name: 'vagrant',
				template: "#{File.dirname(__FILE__)}/stack.yml"}
  end

  config.vm.define 'server-1' do |s|
    s.vm.provider :openstack do |os, override|
      os.server_name = '04_Heat_Stack-1'
      override.ssh.username = ENV['OS_SSH_USERNAME']
    end
  end

  config.vm.define 'server-2' do |s|
    s.vm.provider :openstack do |os, override|
      os.server_name = '04_Heat_Stack-2'
      override.ssh.username = ENV['OS_SSH_USERNAME']
    end
  end
end
