require 'vagrant-openstack-provider'

Vagrant.configure("2") do |config|

  config.vm.box = 'openstack'
  config.vm.box_url = 'https://github.com/ggiamarchi/vagrant-openstack/raw/master/source/dummy.box'

  config.ssh.private_key_path = ENV['OS_KEYPAIR_PRIVATE_KEY']
  config.ssh.pty = true
  config.ssh.shell = ENV['OS_SSH_SHELL']

  config.vm.provider :openstack do |os|
    os.username               = ENV['OS_USERNAME']
    os.password               = ENV['OS_PASSWORD']
    os.openstack_auth_url     = ENV['OS_AUTH_URL']
    os.openstack_compute_url  = ENV['OS_COMPUTE_URL']
    os.openstack_network_url  = ENV['OS_NETWORK_URL']
    os.tenant_name            = ENV['OS_TENANT_NAME']
    os.keypair_name           = ENV['OS_KEYPAIR_NAME']
    os.ssh_timeout            = ENV['OS_SSH_TIMEOUT'].to_i
    os.sync_method            = ENV['OS_SYNC_METHOD']
  end

  config.vm.define 'test' do |test|
    test.vm.provider :openstack do |os|
      os.floating_ip  = ENV['OS_FLOATING_IP']
      os.flavor       = ENV['OS_FLAVOR']
      os.image        = ENV['OS_IMAGE']
      os.ssh_username = ENV['OS_SSH_USERNAME']
    end
    test.vm.provision 'shell', inline: 'echo "SUCCESS" > /tmp/test_shell_provision'
  end

end
