# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# This is quite the minimal configuration necessary
# to start an OpenStack instance using Vagrant on
# an OpenStack with Keystone v3 API
#
Vagrant.configure('2') do |config|

  config.ssh.username = ENV['OS_SSH_USERNAME']

  config.vm.provider :openstack do |os|
    os.server_name                      = '05_keystone_v3'
    os.identity_api_version             = '3'
    os.openstack_auth_url               = ENV['OS_AUTH_URL']
    os.project_name                     = ENV['OS_PROJECT_NAME']
    os.domain_name                      = ENV['OS_PROJECT_DOMAIN_ID']
    os.username                         = ENV['OS_USERNAME']
    os.password                         = ENV['OS_PASSWORD']
    os.region                           = ENV['OS_REGION_NAME']
    os.floating_ip_pool                 = ENV['OS_FLOATING_IP_POOL']
    os.floating_ip_pool_always_allocate = (ENV['OS_FLOATING_IP_ALWAYS_ALLOCATE'] == 'true')
    os.flavor                           = ENV['OS_FLAVOR']
    os.image                            = ENV['OS_IMAGE']
    os.networks                        << ENV['OS_NETWORK']
  end
end
