# -*- mode: ruby -*-
# vi: set ft=ruby :

#
# This is quite the minimal configuration necessary
# to start an OpenStack instance using Vagrant.
#
# This example assumes a floating IP is needed to
# reach the machine, although you might remove the
# floating_ip_pool parameter if you are able to join
# the instance using its private IP address (e.g.
# through a VPN).
#
Vagrant.configure('2') do |config|

  config.ssh.username = ENV['OS_SSH_USERNAME']

  config.vm.provider :openstack do |os, ov|
    os.server_name                      = '01_simple'
    os.openstack_auth_url               = ENV['OS_AUTH_URL']
    os.tenant_name                      = ENV['OS_TENANT_NAME']
    os.username                         = ENV['OS_USERNAME']
    os.password                         = ENV['OS_PASSWORD']
    os.region                           = ENV['OS_REGION_NAME']
    os.floating_ip_pool                 = ENV['OS_FLOATING_IP_POOL']
    os.floating_ip_pool_always_allocate = (ENV['OS_FLOATING_IP_ALWAYS_ALLOCATE'] == 'true')
    os.flavor                           = ENV['OS_FLAVOR']
    os.image                            = ENV['OS_IMAGE']
    os.networks                        << ENV['OS_NETWORK']

    ov.nfs.functional = false
  end
end
