AllCops:
  Exclude:
    - 'out/**/*'
    - '**/Vagrantfile'

Style/FileName:
  Enabled: false

Style/Encoding:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Severity: warning
  Max: 15

Metrics/MethodLength:
  Max: 60

Metrics/LineLength:
  Max: 150

Metrics/ParameterLists:
  Max: 6

Metrics/AbcSize:
  Max: 110

Metrics/PerceivedComplexity:
  Max: 45

Metrics/ModuleLength:
  Max: 200
