source 'https://rubygems.org'

gemspec

group :development do
  gem 'vagrant', git: 'https://github.com/mitchellh/vagrant.git', tag: 'v2.3.3'
  gem 'appraisal', '1.0.0'
  gem 'rubocop', '0.29.0', require: false
  gem 'coveralls', require: false
  gem 'rspec-its'
end

group :debug do
  gem 'byebug'
end
