#!/bin/bash

export OS_AUTH_URL=https://cloud.numergy.com/identity/v2.0/tokens
export OS_COMPUTE_URL=https://cloud.numergy.com/compute/v2

if [ -z "$OS_USERNAME" ]; then
  echo "Please enter your OpenStack tenant name: "
  read -sr OS_TENANT_NAME_INPUT
  export OS_TENANT_NAME=$OS_TENANT_NAME_INPUT
fi

if [ -z "$OS_USERNAME" ]; then
  echo "Please enter your OpenStack username: "
  read -sr OS_USERNAME_INPUT
  export OS_USERNAME=$OS_USERNAME_INPUT
fi

if [ -z "$OS_PASSWORD" ]; then
  echo "Please enter your OpenStack Password: "
  read -sr OS_PASSWORD_INPUT
  export OS_PASSWORD=$OS_PASSWORD_INPUT
fi
