#!/bin/bash

export OS_AUTH_URL=https://cloud.numergy.com:5000/v2.0/tokens
export OS_COMPUTE_URL=https://cloud.numergy.com:8774/v2

# With the addition of Keystone we have standardized on the term **tenant**
# as the entity that owns the resources.
export OS_TENANT_NAME="PaaS"

# In addition to the owning entity (tenant), openstack stores the entity
# performing the action as the **user**.
if [ -z "$OS_USERNAME" ]; then
  echo "Please enter your OpenStack username: "
  read -sr OS_USERNAME_INPUT
  export OS_USERNAME=$OS_USERNAME_INPUT
fi

# With Keystone you pass the keystone password.
if [ -z "$OS_PASSWORD" ]; then
  echo "Please enter your OpenStack Password: "
  read -sr OS_PASSWORD_INPUT
  export OS_PASSWORD=$OS_PASSWORD_INPUT
fi
