# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby-version: ['2.7']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: |
        cd source
        bundle install
    - name: Run tests
      run: |
        cd source
        bundle exec rake
    - name: Build gem package
      run: |
        cd source
        gem build *.gemspec
        mv $(ls -1 | grep -e "\.gem$") vagrant-openstack-provider.gem
    - name: Archive gem package
      uses: actions/upload-artifact@v3
      with:
        name: vagrant-openstack-provider.gem
        path: source/vagrant-openstack-provider.gem
